//==============================================================================
// Generated Date: 2025-10-17T23:05:40.092863
//
// Generated By language_helper - Do Not Modify By Hand
//==============================================================================

// ignore_for_file: prefer_single_quotes

part of '../language_data.dart';

const analysisLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: ./lib/page_asset.dart
  ///===========================================================================
  "@path_./lib/page_asset.dart": '',
  'Asset': 'Asset',
  'This is the line 1': 'This is the line 1',
  'This is the line 2': 'This is the line 2',
  'Change language': 'Change language',

  ///===========================================================================
  /// Path: ./lib/main.dart
  ///===========================================================================
  "@path_./lib/main.dart": '',
  'Hello': 'Hello',
  // 'Hello': 'Hello',  // Duplicated
  // 'Hello': 'Hello',  // Duplicated
  // 'Hello': 'Hello',  // Duplicated
  // 'Hello': 'Hello',  // Duplicated
  'This is @number dollar': 'This is @number dollar',
  // 'This is @number dollar': 'This is @number dollar',  // Duplicated
  // 'This is @number dollar': 'This is @number dollar',  // Duplicated
  // 'This is a contains variable line $mounted': 'This is a contains variable line $mounted',  // Contains variable
  'This text will be changed when the data added':
      'This text will be changed when the data added',
  'Other Page': 'Other Page',
  'Text will be changed': 'Text will be changed',
  'Text will be not changed': 'Text will be not changed',
  // 'Change language': 'Change language',  // Duplicated
};
