//==============================================================================
// Generated Date: 2025-10-24T14:22:51.053416
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes
import 'package:language_helper/language_helper.dart';

final enLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: page_asset.dart
  ///===========================================================================
  "@path_page_asset.dart": "",
  "Asset": 'Asset',
  "This is the line 1": 'This is the line 1',
  "This is the line 2": 'This is the line 2',
  "Change language": 'Change language',

  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Hello": 'Hello',
  "This is @number dollar": const LanguageConditions(
    param: 'number',
    conditions: {
      '0': 'This is zero dollar',
      '1': 'This is one dollar',
      '_': 'This is @number dollars',
    },
  ),
  "Other Page": 'Other Page',
  "Text will be changed": 'Text will be changed',
  "Text will be not changed": 'Text will be not changed',
};
