//==============================================================================
// Generated Date: 2025-10-24T14:22:51.053416
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

final viLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: page_asset.dart
  ///===========================================================================
  "@path_page_asset.dart": "",
  "Asset": 'Asset',
  "This is the line 1": 'Đây là dòng thứ 1',
  "This is the line 2": 'Đây là dòng thứ 2',
  "Change language": 'Thay đổi ngôn ngữ',

  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Hello": 'Xin Chào',
  "This is @number dollar": 'Đây là @number đô-la',
  "Other Page": 'Trang Khác',
  "Text will be changed": 'Chữ sẽ thay đổi',
  "Text will be not changed": 'Chữ không thay đổi',
};
