//==============================================================================
// Generated Date: 2025-10-28T09:39:14.146785
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

import 'package:language_helper/language_helper.dart';

const enLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Language Helper Demo',
  "Home": 'Home',
  "Dart Map": 'Dart Map',
  "JSON": 'JSON',
  "Network": 'Network',
  "Multi": 'Multi',
  "Advanced": 'Advanced',
  "English": 'English',
  "Vietnamese": 'Vietnamese',
  "Spanish": 'Spanish',
  "French": 'French',
  "Welcome to Language Helper": 'Welcome to Language Helper',
  "A comprehensive localization solution for Flutter":
      "A comprehensive localization solution for Flutter",
  "Language Statistics": 'Language Statistics',
  "Current Language": "Current Language",
  "Supported Languages": 'Supported Languages',
  "Current Locale": 'Current Locale',
  "Device Locale": 'Device Locale',
  "Translation Examples": "Translation Examples",
  "Simple Translation": 'Simple Translation',
  "Hello @{name}": 'Hello @{name}',
  "Parameter Translation": 'Parameter Translation',
  "Conditional Translation": 'Conditional Translation',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': 'You have no items',
      '1': 'You have one item',
      '_': 'You have @{count} items',
    },
  ),
  "Switch Language": "Switch Language",

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Network Data Example": "Network Data Example",
  "Loading translations from network...":
      'Loading translations from network...',
  "This may take a few seconds": 'This may take a few seconds',
  "Failed to load network translations": 'Failed to load network translations',
  "Retry": 'Retry',
  "Network Data Source": "Network Data Source",
  "Load translations from remote servers or APIs.":
      'Load translations from remote servers or APIs.',
  "Network translations loaded successfully":
      'Network translations loaded successfully',
  "Select Language": 'Select Language',
  "Code Example": 'Code Example',

  ///===========================================================================
  /// Path: pages/advanced_features_page.dart
  ///===========================================================================
  "@path_pages/advanced_features_page.dart": "",
  "Language changed from @{from} to @{to}":
      "Language changed from @{from} to @{to}",
  "Advanced Features": 'Advanced Features',
  "Advanced Language Features": "Advanced Language Features",
  "Master complex conditions, dynamic parameters, and language change listeners.":
      "Master complex conditions, dynamic parameters, and language change listeners.",
  "Complex Conditional Translations": "Complex Conditional Translations",
  "Notifications": "Notifications",
  "You have @{count} notification": "You have @{count} notification",
  "Time Format": "Time Format",
  "Time format": "Time format",
  "Plural Items": "Plural Items",
  "Plural items": "Plural items",
  "Dynamic Parameter Injection": "Dynamic Parameter Injection",
  "Welcome Message": "Welcome Message",
  "Welcome @{name}": "Welcome @{name}",
  "Timestamp": "Timestamp",
  "Current timestamp": "Current timestamp",
  "Device Info": "Device Info",
  "Device info": "Device info",
  "Language Change Listener": 'Language Change Listener',
  "Change language to see listener notifications.":
      'Change language to see listener notifications.',
  "Is Initialized": "Is Initialized",
  "Data Sources": "Data Sources",

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Multiple Sources Example": "Multiple Sources Example",
  "Multiple Data Sources": 'Multiple Data Sources',
  "Combine multiple translation sources with automatic priority handling.":
      "Combine multiple translation sources with automatic priority handling.",
  "Data Source Priority": "Data Source Priority",
  "From Primary Source": "From Primary Source",
  "From Secondary Source": "From Secondary Source",
  "Multiple sources working": "Multiple sources working",
  "Dynamic Addition": "Dynamic Addition",
  "This text was added dynamically": "This text was added dynamically",
  "Dynamic Data Management": "Dynamic Data Management",
  "Add": "Add",
  "Dynamic data added successfully!": 'Dynamic data added successfully!',

  ///===========================================================================
  /// Path: pages/json_asset_page.dart
  ///===========================================================================
  "@path_pages/json_asset_page.dart": "",
  "JSON Asset Example": "JSON Asset Example",
  "Loading translations...": 'Loading translations...',
  "JSON Asset Data Source": 'JSON Asset Data Source',
  "Load translations from JSON files stored in your app assets.":
      "Load translations from JSON files stored in your app assets.",

  ///===========================================================================
  /// Path: pages/dart_map_page.dart
  ///===========================================================================
  "@path_pages/dart_map_page.dart": "",
  "Dart Map Example": "Dart Map Example",
  "Dart Map Data Source": 'Dart Map Data Source',
  "Define translations directly in Dart using maps and LanguageConditions.":
      'Define translations directly in Dart using maps and LanguageConditions.',
  "Key Features": 'Key Features',
};
