//==============================================================================
// Generated Date: 2025-10-27T20:31:59.856989
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

import 'package:language_helper/language_helper.dart';

const enLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Language Helper Demo',
  "Home": 'Home',
  "Dart Map Example": 'Dart Map Example',
  "JSON Asset Example": 'JSON Asset Example',
  "Network Data Example": 'Network Data Example',
  "Multiple Sources Example": 'Multiple Sources Example',
  "Advanced Features": 'Advanced Features',
  "English": 'English',
  "Vietnamese": 'Vietnamese',
  "Spanish": 'Spanish',
  "French": 'French',
  "Welcome to Language Helper": 'Welcome to Language Helper',
  "This is a comprehensive example": 'This is a comprehensive example',
  "Language Statistics": 'Language Statistics',
  "Current language": 'Current language',
  "Supported Languages": 'Supported Languages',
  "Current Locale": 'Current Locale',
  "Device Locale": 'Device Locale',
  "Simple Translation": 'Simple Translation',
  "Hello @{name}": 'Hello @{name}',
  "Parameter Translation": 'Parameter Translation',
  "Conditional Translation": 'Conditional Translation',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': 'You have no items',
      '1': 'You have one item',
      '_': 'You have @{count} items',
    },
  ),

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Loading translations from network...":
      'Loading translations from network...',
  "Failed to load network translations": 'Failed to load network translations',
  "Retry": 'Retry',
  "Network translations loaded successfully":
      'Network translations loaded successfully',

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Add New Translation": 'Add New Translation',
  "Remove Translation": 'Remove Translation',
};
