//==============================================================================
// Generated Date: 2025-10-27T20:31:59.856989
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

import 'package:language_helper/language_helper.dart';

const esLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Demo de Language Helper',
  "Home": 'Inicio',
  "Dart Map Example": 'Ejemplo de Dart Map',
  "JSON Asset Example": 'Ejemplo de JSON Asset',
  "Network Data Example": 'Ejemplo de datos de red',
  "Multiple Sources Example": 'Ejemplo de múltiples fuentes',
  "Advanced Features": 'Características avanzadas',
  "English": 'Inglés',
  "Vietnamese": 'Vietnamita',
  "Spanish": 'Español',
  "French": 'Francés',
  "Welcome to Language Helper": 'Bienvenido a Language Helper',
  "This is a comprehensive example": 'Este es un ejemplo completo',
  "Language Statistics": 'Estadísticas de idioma',
  "Current language": 'Idioma actual',
  "Supported Languages": 'Idiomas soportados',
  "Current Locale": 'Locale actual',
  "Device Locale": 'Locale del dispositivo',
  "Simple Translation": 'Traducción simple',
  "Hello @{name}": 'Hola @{name}',
  "Parameter Translation": 'Traducción con parámetros',
  "Conditional Translation": 'Traducción condicional',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': 'No tienes elementos',
      '1': 'Tienes un elemento',
      '_': 'Tienes @{count} elementos',
    },
  ),

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Loading translations from network...":
      'Cargando traducciones desde la red...',
  "Failed to load network translations": 'Error al cargar traducciones de red',
  "Retry": 'Reintentar',
  "Network translations loaded successfully":
      'Traducciones de red cargadas exitosamente',

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Add New Translation": 'Agregar nueva traducción',
  "Remove Translation": 'Eliminar traducción',
};
