//==============================================================================
// Generated Date: 2025-10-28T11:55:55.538963
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars

import 'package:language_helper/language_helper.dart';

const esLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Demo de Language Helper',
  "Home": 'Inicio',
  "Dart Map": 'Dart Map',
  "JSON": 'JSON',
  "Network": 'Red',
  "Multi": 'Multi',
  "Advanced": 'Avanzado',
  "English": 'Inglés',
  "Vietnamese": 'Vietnamita',
  "Spanish": 'Español',
  "French": 'Francés',
  "Welcome to Language Helper": 'Bienvenido a Language Helper',
  "A comprehensive localization solution for Flutter":
      "A comprehensive localization solution for Flutter",
  "Language Statistics": 'Estadísticas de idioma',
  "Current Language": "Current Language",
  "Supported Languages": 'Idiomas soportados',
  "Current Locale": 'Locale actual',
  "Device Locale": 'Locale del dispositivo',
  "Translation Examples": "Translation Examples",
  "Simple Translation": 'Traducción simple',
  "Hello @{name}": 'Hola @{name}',
  "Parameter Translation": 'Traducción con parámetros',
  "Conditional Translation": 'Traducción condicional',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': 'No tienes elementos',
      '1': 'Tienes un elemento',
      '_': 'Tienes @{count} elementos',
    },
  ),
  "Switch Language": "Switch Language",

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Network Data Example": "Network Data Example",
  "Loading translations from network...":
      'Cargando traducciones desde la red...',
  "This may take a few seconds": 'Esto puede tomar unos segundos',
  "Failed to load network translations": 'Error al cargar traducciones de red',
  "Retry": 'Reintentar',
  "Network Data Source": "Network Data Source",
  "Load translations from remote servers or APIs.":
      'Cargar traducciones desde servidores remotos o APIs.',
  "Network translations loaded successfully":
      'Traducciones de red cargadas exitosamente',
  "Select Language": 'Seleccionar idioma',
  "Code Example": 'Ejemplo de código',

  ///===========================================================================
  /// Path: pages/advanced_features_page.dart
  ///===========================================================================
  "@path_pages/advanced_features_page.dart": "",
  "Language changed from @{from} to @{to}":
      "Language changed from @{from} to @{to}",
  "Advanced Features": 'Características avanzadas',
  "Advanced Language Features": "Advanced Language Features",
  "Master complex conditions, dynamic parameters, and language change listeners.":
      "Master complex conditions, dynamic parameters, and language change listeners.",
  "Complex Conditional Translations": "Complex Conditional Translations",
  "Notifications": "Notifications",
  "You have @{count} notification": "You have @{count} notification",
  "Time Format": "Time Format",
  "Time format": "Time format",
  "Plural Items": "Plural Items",
  "Plural items": "Plural items",
  "Dynamic Parameter Injection": "Dynamic Parameter Injection",
  "Welcome Message": "Welcome Message",
  "Welcome @{name}": "Welcome @{name}",
  "Timestamp": "Timestamp",
  "Current timestamp": "Current timestamp",
  "Device Info": "Device Info",
  "Device info": "Device info",
  "Language Change Listener": 'Listener de cambio de idioma',
  "Change language to see listener notifications.":
      'Cambia el idioma para ver las notificaciones del listener.',
  "Is Initialized": "Is Initialized",
  "Data Sources": "Data Sources",

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Multiple Sources Example": "Multiple Sources Example",
  "Multiple Data Sources": 'Múltiples fuentes de datos',
  "Combine multiple translation sources with automatic priority handling.":
      "Combine multiple translation sources with automatic priority handling.",
  "Data Source Priority": "Data Source Priority",
  "From Primary Source": "From Primary Source",
  "From Secondary Source": "From Secondary Source",
  "Multiple sources working": "Multiple sources working",
  "Dynamic Addition": "Dynamic Addition",
  "This text was added dynamically": "This text was added dynamically",
  "Dynamic Data Management": "Dynamic Data Management",
  "Add": "Add",
  "Dynamic data added successfully!":
      '¡Datos dinámicos agregados exitosamente!',

  ///===========================================================================
  /// Path: pages/json_asset_page.dart
  ///===========================================================================
  "@path_pages/json_asset_page.dart": "",
  "JSON Asset Example": "JSON Asset Example",
  "Loading translations...": 'Cargando traducciones...',
  "JSON Asset Data Source": 'Fuente de datos JSON Asset',
  "Load translations from JSON files stored in your app assets.":
      "Load translations from JSON files stored in your app assets.",

  ///===========================================================================
  /// Path: pages/dart_map_page.dart
  ///===========================================================================
  "@path_pages/dart_map_page.dart": "",
  "Dart Map Example": "Dart Map Example",
  "Dart Map Data Source": 'Fuente de datos Dart Map',
  "Define translations directly in Dart using maps and LanguageConditions.":
      'Define traducciones directamente en Dart usando mapas y LanguageConditions.',
  "Key Features": 'Características principales',
};
