//==============================================================================
// Generated Date: 2025-10-27T20:31:59.856989
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

import 'package:language_helper/language_helper.dart';

const frLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Démo Language Helper',
  "Home": 'Accueil',
  "Dart Map Example": 'Exemple de Dart Map',
  "JSON Asset Example": 'Exemple de JSON Asset',
  "Network Data Example": 'Exemple de données réseau',
  "Multiple Sources Example": 'Exemple de sources multiples',
  "Advanced Features": 'Fonctionnalités avancées',
  "English": 'Anglais',
  "Vietnamese": 'Vietnamien',
  "Spanish": 'Espagnol',
  "French": 'Français',
  "Welcome to Language Helper": 'Bienvenue dans Language Helper',
  "This is a comprehensive example": 'Ceci est un exemple complet',
  "Language Statistics": 'Statistiques de langue',
  "Current language": 'Langue actuelle',
  "Supported Languages": 'Langues supportées',
  "Current Locale": 'Locale actuel',
  "Device Locale": "Locale de l'appareil",
  "Simple Translation": 'Traduction simple',
  "Hello @{name}": 'Bonjour @{name}',
  "Parameter Translation": 'Traduction avec paramètres',
  "Conditional Translation": 'Traduction conditionnelle',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': "Vous n'avez aucun élément",
      '1': 'Vous avez un élément',
      '_': 'Vous avez @{count} éléments',
    },
  ),

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Loading translations from network...":
      'Chargement des traductions depuis le réseau...',
  "Failed to load network translations":
      'Échec du chargement des traductions réseau',
  "Retry": 'Réessayer',
  "Network translations loaded successfully":
      'Traductions réseau chargées avec succès',

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Add New Translation": 'Ajouter une nouvelle traduction',
  "Remove Translation": 'Supprimer la traduction',
};
