//==============================================================================
// Generated Date: 2025-10-28T11:55:55.538963
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars

import 'package:language_helper/language_helper.dart';

const frLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Démo Language Helper',
  "Home": 'Accueil',
  "Dart Map": 'Dart Map',
  "JSON": 'JSON',
  "Network": "Network",
  "Multi": 'Multi',
  "Advanced": 'Avanzado',
  "English": 'Anglais',
  "Vietnamese": 'Vietnamien',
  "Spanish": 'Espagnol',
  "French": 'Français',
  "Welcome to Language Helper": 'Bienvenue dans Language Helper',
  "A comprehensive localization solution for Flutter":
      "A comprehensive localization solution for Flutter",
  "Language Statistics": 'Statistiques de langue',
  "Current Language": "Current Language",
  "Supported Languages": 'Langues supportées',
  "Current Locale": 'Locale actuel',
  "Device Locale": "Locale de l'appareil",
  "Translation Examples": "Translation Examples",
  "Simple Translation": 'Traduction simple',
  "Hello @{name}": 'Bonjour @{name}',
  "Parameter Translation": 'Traduction avec paramètres',
  "Conditional Translation": 'Traduction conditionnelle',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': "Vous n'avez aucun élément",
      '1': 'Vous avez un élément',
      '_': 'Vous avez @{count} éléments',
    },
  ),
  "Switch Language": "Switch Language",

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Network Data Example": 'Exemple de données réseau',
  "Loading translations from network...":
      'Chargement des traductions depuis le réseau...',
  "This may take a few seconds": 'Cela peut prendre quelques secondes',
  "Failed to load network translations":
      'Échec du chargement des traductions réseau',
  "Retry": 'Réessayer',
  "Network Data Source": "Network Data Source",
  "Load translations from remote servers or APIs.":
      'Charger les traductions depuis des serveurs distants ou des APIs.',
  "Network translations loaded successfully":
      'Traductions réseau chargées avec succès',
  "Select Language": 'Sélectionner la langue',
  "Code Example": 'Exemple de code',

  ///===========================================================================
  /// Path: pages/advanced_features_page.dart
  ///===========================================================================
  "@path_pages/advanced_features_page.dart": "",
  "Language changed from @{from} to @{to}":
      "Language changed from @{from} to @{to}",
  "Advanced Features": 'Fonctionnalités avancées',
  "Advanced Language Features": "Advanced Language Features",
  "Master complex conditions, dynamic parameters, and language change listeners.":
      "Master complex conditions, dynamic parameters, and language change listeners.",
  "Complex Conditional Translations": "Complex Conditional Translations",
  "Notifications": "Notifications",
  "You have @{count} notification": "You have @{count} notification",
  "Time Format": "Time Format",
  "Time format": "Time format",
  "Plural Items": "Plural Items",
  "Plural items": "Plural items",
  "Dynamic Parameter Injection": "Dynamic Parameter Injection",
  "Welcome Message": "Welcome Message",
  "Welcome @{name}": "Welcome @{name}",
  "Timestamp": "Timestamp",
  "Current timestamp": "Current timestamp",
  "Device Info": "Device Info",
  "Device info": "Device info",
  "Language Change Listener": 'Listener de changement de langue',
  "Change language to see listener notifications.":
      'Changez la langue pour voir les notifications du listener.',
  "Is Initialized": "Is Initialized",
  "Data Sources": "Data Sources",

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Multiple Sources Example": "Multiple Sources Example",
  "Multiple Data Sources": 'Sources de données multiples',
  "Combine multiple translation sources with automatic priority handling.":
      "Combine multiple translation sources with automatic priority handling.",
  "Data Source Priority": "Data Source Priority",
  "From Primary Source": "From Primary Source",
  "From Secondary Source": "From Secondary Source",
  "Multiple sources working": "Multiple sources working",
  "Dynamic Addition": "Dynamic Addition",
  "This text was added dynamically": "This text was added dynamically",
  "Dynamic Data Management": "Dynamic Data Management",
  "Add": "Add",
  "Dynamic data added successfully!":
      'Données dynamiques ajoutées avec succès !',

  ///===========================================================================
  /// Path: pages/json_asset_page.dart
  ///===========================================================================
  "@path_pages/json_asset_page.dart": "",
  "JSON Asset Example": "JSON Asset Example",
  "Loading translations...": 'Chargement des traductions...',
  "JSON Asset Data Source": 'Source de données JSON Asset',
  "Load translations from JSON files stored in your app assets.":
      "Load translations from JSON files stored in your app assets.",

  ///===========================================================================
  /// Path: pages/dart_map_page.dart
  ///===========================================================================
  "@path_pages/dart_map_page.dart": "",
  "Dart Map Example": "Dart Map Example",
  "Dart Map Data Source": 'Source de données Dart Map',
  "Define translations directly in Dart using maps and LanguageConditions.":
      'Définir les traductions directement en Dart en utilisant des maps et LanguageConditions.',
  "Key Features": 'Fonctionnalités clés',
};
