//==============================================================================
// Generated Date: 2025-10-27T20:31:59.856989
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

import 'package:language_helper/language_helper.dart';

const viLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Demo Language Helper',
  "Home": 'Trang chủ',
  "Dart Map Example": 'Ví dụ Dart Map',
  "JSON Asset Example": 'Ví dụ JSON Asset',
  "Network Data Example": 'Ví dụ dữ liệu mạng',
  "Multiple Sources Example": 'Ví dụ nhiều nguồn',
  "Advanced Features": 'Tính năng nâng cao',
  "English": 'Tiếng Anh',
  "Vietnamese": 'Tiếng Việt',
  "Spanish": 'Tiếng Tây Ban Nha',
  "French": 'Tiếng Pháp',
  "Welcome to Language Helper": 'Chào mừng đến với Language Helper',
  "This is a comprehensive example": 'Đây là một ví dụ toàn diện',
  "Language Statistics": 'Thống kê ngôn ngữ',
  "Current language": 'Ngôn ngữ hiện tại',
  "Supported Languages": 'Ngôn ngữ được hỗ trợ',
  "Current Locale": 'Locale hiện tại',
  "Device Locale": 'Locale thiết bị',
  "Simple Translation": 'Dịch đơn giản',
  "Hello @{name}": 'Xin chào @{name}',
  "Parameter Translation": 'Dịch có tham số',
  "Conditional Translation": 'Dịch có điều kiện',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': 'Bạn không có mục nào',
      '1': 'Bạn có một mục',
      '_': 'Bạn có @{count} mục',
    },
  ),

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Loading translations from network...": 'Đang tải bản dịch từ mạng...',
  "Failed to load network translations": 'Không thể tải bản dịch từ mạng',
  "Retry": 'Thử lại',

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Add New Translation": 'Thêm bản dịch mới',
  "Remove Translation": 'Xóa bản dịch',
};
