//==============================================================================
// Generated Date: 2025-10-28T09:39:14.146785
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

import 'package:language_helper/language_helper.dart';

const viLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Language Helper Demo": 'Demo Language Helper',
  "Home": 'Trang chủ',
  "Dart Map": 'Dart Map',
  "JSON": "JSON",
  "Network": 'Mạng',
  "Multi": 'Nhiều',
  "Advanced": 'Nâng cao',
  "English": 'Tiếng Anh',
  "Vietnamese": 'Tiếng Việt',
  "Spanish": 'Tiếng Tây Ban Nha',
  "French": 'Tiếng Pháp',
  "Welcome to Language Helper": 'Chào mừng đến với Language Helper',
  "A comprehensive localization solution for Flutter":
      "A comprehensive localization solution for Flutter",
  "Language Statistics": 'Thống kê ngôn ngữ',
  "Current Language": "Current Language",
  "Supported Languages": 'Ngôn ngữ được hỗ trợ',
  "Current Locale": 'Locale hiện tại',
  "Device Locale": 'Locale thiết bị',
  "Translation Examples": "Translation Examples",
  "Simple Translation": 'Dịch đơn giản',
  "Hello @{name}": 'Xin chào @{name}',
  "Parameter Translation": 'Dịch có tham số',
  "Conditional Translation": 'Dịch có điều kiện',
  "You have @{count} item": LanguageConditions(
    param: 'count',
    conditions: {
      '0': 'Bạn không có mục nào',
      '1': 'Bạn có một mục',
      '_': 'Bạn có @{count} mục',
    },
  ),
  "Switch Language": "Switch Language",

  ///===========================================================================
  /// Path: pages/network_data_page.dart
  ///===========================================================================
  "@path_pages/network_data_page.dart": "",
  "Network Data Example": "Network Data Example",
  "Loading translations from network...": 'Đang tải bản dịch từ mạng...',
  "This may take a few seconds": 'Điều này có thể mất vài giây',
  "Failed to load network translations": 'Không thể tải bản dịch từ mạng',
  "Retry": 'Thử lại',
  "Network Data Source": "Network Data Source",
  "Load translations from remote servers or APIs.":
      'Tải bản dịch từ máy chủ từ xa hoặc APIs.',
  "Network translations loaded successfully":
      "Network translations loaded successfully",
  "Select Language": 'Chọn ngôn ngữ',
  "Code Example": 'Ví dụ mã',

  ///===========================================================================
  /// Path: pages/advanced_features_page.dart
  ///===========================================================================
  "@path_pages/advanced_features_page.dart": "",
  "Language changed from @{from} to @{to}":
      "Language changed from @{from} to @{to}",
  "Advanced Features": 'Tính năng nâng cao',
  "Advanced Language Features": "Advanced Language Features",
  "Master complex conditions, dynamic parameters, and language change listeners.":
      "Master complex conditions, dynamic parameters, and language change listeners.",
  "Complex Conditional Translations": "Complex Conditional Translations",
  "Notifications": "Notifications",
  "You have @{count} notification": "You have @{count} notification",
  "Time Format": "Time Format",
  "Time format": "Time format",
  "Plural Items": "Plural Items",
  "Plural items": "Plural items",
  "Dynamic Parameter Injection": "Dynamic Parameter Injection",
  "Welcome Message": "Welcome Message",
  "Welcome @{name}": "Welcome @{name}",
  "Timestamp": "Timestamp",
  "Current timestamp": "Current timestamp",
  "Device Info": "Device Info",
  "Device info": "Device info",
  "Language Change Listener": 'Listener thay đổi ngôn ngữ',
  "Change language to see listener notifications.":
      'Thay đổi ngôn ngữ để xem thông báo từ listener.',
  "Is Initialized": "Is Initialized",
  "Data Sources": "Data Sources",

  ///===========================================================================
  /// Path: pages/multiple_sources_page.dart
  ///===========================================================================
  "@path_pages/multiple_sources_page.dart": "",
  "Multiple Sources Example": "Multiple Sources Example",
  "Multiple Data Sources": 'Nhiều nguồn dữ liệu',
  "Combine multiple translation sources with automatic priority handling.":
      "Combine multiple translation sources with automatic priority handling.",
  "Data Source Priority": "Data Source Priority",
  "From Primary Source": "From Primary Source",
  "From Secondary Source": "From Secondary Source",
  "Multiple sources working": "Multiple sources working",
  "Dynamic Addition": "Dynamic Addition",
  "This text was added dynamically": "This text was added dynamically",
  "Dynamic Data Management": "Dynamic Data Management",
  "Add": "Add",
  "Dynamic data added successfully!": 'Dữ liệu động được thêm thành công!',

  ///===========================================================================
  /// Path: pages/json_asset_page.dart
  ///===========================================================================
  "@path_pages/json_asset_page.dart": "",
  "JSON Asset Example": 'Ví dụ JSON Asset',
  "Loading translations...": 'Đang tải bản dịch...',
  "JSON Asset Data Source": 'Nguồn dữ liệu JSON Asset',
  "Load translations from JSON files stored in your app assets.":
      "Load translations from JSON files stored in your app assets.",

  ///===========================================================================
  /// Path: pages/dart_map_page.dart
  ///===========================================================================
  "@path_pages/dart_map_page.dart": "",
  "Dart Map Example": "Dart Map Example",
  "Dart Map Data Source": 'Nguồn dữ liệu Dart Map',
  "Define translations directly in Dart using maps and LanguageConditions.":
      'Định nghĩa bản dịch trực tiếp trong Dart bằng cách sử dụng maps và LanguageConditions.',
  "Key Features": 'Tính năng chính',
};
