//==============================================================================
// Generated Date: 2023-12-30T23:13:39.711829
//
// Code Generated By language_helper - Do Not Modify By Hand
//==============================================================================

// ignore_for_file: prefer_single_quotes

part of 'language_data.dart';

const analysisLanguageData = {
  ///===========================================================================
  /// Path: ./lib/main.dart
  ///===========================================================================
  'Hello': 'Hello',
  // 'Hello': 'Hello',  // Duplicated
  // 'Hello': 'Hello',  // Duplicated
  'Change language': 'Change language',
  'Analyze languages': 'Analyze languages',
  // 'Hello': 'Hello',  // Duplicated
  // 'Hello': 'Hello',  // Duplicated
  'This is @number dollar': 'This is @number dollar',
  // 'This is @number dollar': 'This is @number dollar',  // Duplicated
  // 'This is @number dollar': 'This is @number dollar',  // Duplicated
  // 'This is a contains variable line $mounted': 'This is a contains variable line $mounted',  // Contains variable
  'This text will be changed when the data added':
      'This text will be changed when the data added',
  'Other Page': 'Other Page',
  'Text will be changed': 'Text will be changed',
  'Text will be not changed': 'Text will be not changed',
  // 'Change language': 'Change language',  // Duplicated
};
