//==============================================================================
// Generated Date: 2024-01-23T23:36:40.202737
//
// Code Generated By language_helper - Do Not Modify By Hand
//==============================================================================

// ignore_for_file: prefer_single_quotes

part of 'language_data.dart';

const analysisLanguageData = {
  ///===========================================================================
  /// Path: ./lib/page_asset.dart
  ///===========================================================================
  '@path_0': './lib/page_asset.dart',
  'Asset': 'Asset',
  'This is the line 1': 'This is the line 1',
  'This is the line 2': 'This is the line 2',

  ///===========================================================================
  /// Path: ./lib/main.dart
  ///===========================================================================
  '@path_1': './lib/main.dart',
  'Hello': 'Hello',
  // 'Hello': 'Hello',  // Duplicated
  // 'Hello': 'Hello',  // Duplicated
  'Change language': 'Change language',
  'Analyze languages': 'Analyze languages',
  // 'Hello': 'Hello',  // Duplicated
  // 'Hello': 'Hello',  // Duplicated
  'This is @number dollar': 'This is @number dollar',
  // 'This is @number dollar': 'This is @number dollar',  // Duplicated
  // 'This is @number dollar': 'This is @number dollar',  // Duplicated
  // 'This is a contains variable line $mounted': 'This is a contains variable line $mounted',  // Contains variable
  'This text will be changed when the data added':
      'This text will be changed when the data added',
  'Export JSON': 'Export JSON',
  'Other Page': 'Other Page',
  'Text will be changed': 'Text will be changed',
  'Text will be not changed': 'Text will be not changed',
  // 'Change language': 'Change language',  // Duplicated
};
