//==============================================================================
// Generated Date: 2025-10-24T14:22:51.053416
//
// Generated by language_helper. Please do not modify by hand
//==============================================================================

// Keeps format for the parser
// ignore_for_file: always_use_package_imports

import 'package:language_helper/language_helper.dart';

import 'languages/en.dart';
import 'languages/vi.dart';

final LazyLanguageData languageData = {
  LanguageCodes.en: () => enLanguageData,
  LanguageCodes.vi: () => viLanguageData,
};
