//==============================================================================
// Generated Date: 2025-10-28T11:55:55.538963
//
// Generated by language_helper. Please do not modify by hand
//==============================================================================

// Keeps format for the parser
// ignore_for_file: always_use_package_imports, lines_longer_than_80_chars

import 'package:language_helper/language_helper.dart';

import 'data/en.dart';
import 'data/es.dart';
import 'data/fr.dart';
import 'data/vi.dart';

final LazyLanguageData languageData = {
  LanguageCodes.en: () => enLanguageData,
  LanguageCodes.es: () => esLanguageData,
  LanguageCodes.fr: () => frLanguageData,
  LanguageCodes.vi: () => viLanguageData,
};
