name: GitHub Actions
run-name: ${{ github.actor }}
on: [push]
jobs:
  Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
